### ISSUE TITLE
Non-static method Hashids::decode() should not be called statically

### ISSUE THREAD

**Issue by TaifRaoof** [Torann/laravel-hashids#6]
Hi this error appear  when use Hashids::encode or Hashids::decode in my ArtController 
" Non-static method Hashids\Hashids::decode() should not be called statically, assuming $this from incompatible context "

**Comment by IonutRusen** [comment]
same error here!

**Comment by TaifRaoof** [comment]
i solved this error by define protected $hashids in class and then  called this line below in __construct() then 
`        $this->hashids = new Hashids('put here any key for security', put here length);
`  
@IonutRusen

**Comment by chungnd10** [comment]
I have encountered the same error, and here is how I solved the problem, you can refer.
Please use:
use Vinkla\Hashids\Facades\Hashids;
instead of:
use Hashids\Hashids;
